### ISSUE TITLE
LoadModel broken

### ISSUE THREAD

**Issue by 89z** [snakx/YouTubeApiSharp#1]
This code:

https://github.com/snakx/YouTubeApiSharp/blob/6434a04a547adbd42f69f71b6e86696ec03d047f/src/YouTubeApiSharp/YouTubeApiSharp/API/DownloadUrlResolver.cs#L84-L90

Uses this function:

https://github.com/snakx/YouTubeApiSharp/blob/6434a04a547adbd42f69f71b6e86696ec03d047f/src/YouTubeApiSharp/YouTubeApiSharp/API/DownloadUrlResolver.cs#L344-L347

However that URL is not longer valid. Here is a test:

<https://www.youtube.com/get_video_info?html5=1&video_id=NMYIVsdGfoo&eurl=https://youtube.googleapis.com/v/NMYIVsdGfoo&c=TVHTML5&cver=6.20180913>

**Comment by thisistorsten** [comment]
Try the latest releaae please. In my case it works.

Please report back if it wont attaching the error code please.

Steven Penny ***@***.***> schrieb am Fr., 18. Juni 2021,
22:01:

**Comment by 89z** [comment]
Im not sure what release you are talking about. I pulled that code directly from `main`, and its currently not valid.

**Comment by thisistorsten** [comment]
Whats the return code when you try? Please give me more informations 👍🏻

Steven Penny ***@***.***> schrieb am Fr., 18. Juni 2021,
22:49:

**Comment by 89z** [comment]
I am telling you that it doesnt work, as the `Microformat` struct no longer exists in the response:

~~~
PS C:\> curl 'https://www.youtube.com/get_video_info?html5=1&video_id=NMYIVsdGfoo&eurl=https://youtube.googleapis.com/v/NMYIVsdGfoo&c=TVHTML5&cver=6.20180913' |
>> Select-String Microformat
~~~

**Comment by thisistorsten** [comment]
Then use my other solution reading it from page directly. Then i send a
patch and comment it out 😉

Steven Penny ***@***.***> schrieb am Fr., 18. Juni 2021,
23:00:
